### ISSUE TITLE
Module - How-to

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#3]
**Updated 10-05-19 (Chrismclarke)**

**v0.3.0**
- [x] Add notification for “under development” : Beta bar at the top
- [x] Archive current `master` branch work on discussion & other section than how-to (#441)
- [x] Update UI of pages :
    - [x] How-to list view (#419)
    - [x] How-to create post (#440)
    - [x] How-to post view (#420)
    - [x] Remove material-ui (rebuild components)
- [x] Enhance create how-to
    - [x] Local image compression
    - [x] Attachment upload and limitations (e.g. size, number, filetype)
    - [x] Add tags
    - [x] Upload progress updates
    - [x] Add react-final-form bindings for all inputs
    - [x] Upload multiple images per step
- [x] Minor fixes/enhancements
    - [x] Limit create to logged in users only (#457)
    - [x] Link username and avatar to created by message (#467)

**backlog**
- Migrate production site data to use new format (tutorials and profiles) (#468)
- List view improvements
    - filterbar
    - search
    - viewcounts
- Create how-to improvements
    - Add project
    - Reorder images (#227)
    - Max images formats (handle/block gifs)
    - Add embed video
    - Add contributions guidelines
    - Edit how-to (#103)
    - Multiple currency for how-to cost
    - Add tutorial cost field (single currency - euro) (under discussion)
- Single view improvements
    - Show video
    - Add/display comment
    - Favourite/saved how-tos
    - Rating/upvote/useful mark system
    - Set active post on list click and skip db query for post by slug if matches active
    - Image display on mobile (possibly less content padding and lightbox viewer)
    - x days ago also include months/years

**Overview:**
The How-To's page (previously Documentation) is a tool for people to share their processes, technics, hacks, products and findings. Heavily influenced by tools like iFixit and Instructables will help global human knowledge to exponentially expand. 

In this module we have 3 main pages:
* How-to overview (#419)
* How-to post view (#420)
* How-to create post (#440)

**Latest design resources:**
Prototype
https://www.figma.com/proto/OZ5xbZYR4ZKNBijrs9kPJnbu/OneArmy-Platform?node-id=458%3A2&viewport=52%2C441%2C0.027&scaling=scale-down-width

**Epics:**
https://docs.google.com/spreadsheets/d/1pkLRKCbQiJOtQwWEhVNgSTvDWf5SnVAz10vMo4k-LNg/edit#gid=0

Any questions post in the comments

**Comment by chrismclarke** [comment]
now things being handled in smaller issues so feels less relevant to keep open. Closing.
