### ISSUE TITLE
Module - Users/Profiles

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#8]
_Updated 06/05/19_

## Roadmap
**Core Functionality**
- [ ] View alt user profile
- [ ] Upload avatar
- [x] User Register Form
- [x] User Login form and functionality
- [x] Migrate DH site data
- [x] Update profile information
- [x] Password forgotten/reset link
- [x] Password change
- [x] User email confirmation (+resend link)

**Backlog**
- Automated testing for all features
- User profile delete
- User avatar thumbnails (smaller sized)
- Crop avatar
- Migrate DH avatar
- Country picker for profile field
- Additional auth for user migrate

**Under consideration**
- Change mention name

## User Module Epics

- As a user, I can login with an email and an email address
- As a user can describe basic information about themselves
- As a user will have a profile page to list their information
- As a user needs to verify their email before being able to login

**Comment by chrismclarke** [comment]
From PR #357 (for reference):
@kopecms mentioned still to do:

* email verification (now user is automaticly logged in after sign up)
* handling error while sign up proccess (delete create entry in Authentication?)
* handle additional fieds in form (avatar, nickname itd..)
* add some tests

@chrismclarke gave various bits of feedback, possibly even some of it useful (:p). To-do could be broken down into separate issues or just left to @kopecms to get on with if preferred.

Currently pending mockups for user profile page, @mattia-io says should get over in the next couple days. Also suggested that once implemented @mattia-io might also want to give a once-over to the automatic email that will be sent out to verify email address (will share placeholder when there).

**Comment by chrismclarke** [comment]
now things being handled in smaller issues so feels less relevant to keep open. Closing.
